//DeleteStockServlet.java
/*********************************************************************************
File Name :			DeleteStockServlet.java
Description :		Servlet for deleting stock information
Version :			v0.1
*********************************************************************************/

package Stocks_XMLApplication;

import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;

public class DeleteStockServlet extends HttpServlet {
	
	/**
	 *	Method Name: init
	 *  Method Desc: initialize the servlet
	 *  @param ServletConfig -- the servlet confiuration
	 *	@exception ServletException -- in case any errors occurs during initialization
	 *	@return -- void
	 */
	public void init(ServletConfig config) throws ServletException {
		super.init(config);
	}	
	
	/*
	 *	Method Name: doGet
	 *	Method Desc: Handle Get operations of the servlet
	 *	@param HttpServletRequest -- the incoming request
	 *	@param HttpServletResponse -- the outgoing response
	 *	@exception ServletException -- errors generated by servlet
	 *	@exception IOException -- for IO operation errors
	 */
	 public void doGet(HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException
	{
		HttpSession session = request.getSession();
		
		try {
			// setup stock information
			String companySymbol = request.getParameter("symbol");
			Stocks_XMLApplication.StockDatabase stdb = new Stocks_XMLApplication.StockDatabase();
			// delete stock information
			if (stdb.deleteStock(companySymbol)) {
				Stocks_XMLApplication.StringBean s = new Stocks_XMLApplication.StringBean();				
				s.setMessage(stdb.getMessage());
				session.setAttribute("msgInfo", s);
				// forward to StockMessage to display stock information and message
				goToPage(messagePage, request, response);
			}
		} catch(NullPointerException npe) {
			Stocks_XMLApplication.StringBean sb = new Stocks_XMLApplication.StringBean();
			sb.setMessage("<font color=\"red\"> Error in Input </font>");
			// set message information
			session.setAttribute("msgInfo", sb);
			// forward to JSP page to display message
			goToPage(messagePage, request, response);
		}
	}

	/*
	 *	Method Name: doPost
	 *	Method Desc: Handle Post operations of the servlet
	 *	@param HttpServletRequest -- the incoming request
	 *	@param HttpServletResponse -- the outgoing response
	 *	@exception ServletException -- errors generated by servlet
	 *	@exception IOException -- for IO operation errors
	 */
	 public void doPost(HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException
	{
		doGet(request, response);
	}
	
	/*
	 *	Method Name: goToPage
	 *	Method Desc: A generic helper method that supports processRequest to forward 
	 *					to a particular page
	 * @param  address - the URL page to go to
	 * @param  request - an HttpServletRequest 
	 * @param  response - an HttpServletResponse
	 * @exception ServletException, IOException	
	 * Original source from More Servlets & Java Server Pages(page 224)
	 **/
	private void goToPage ( String address, HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException 
	{
		RequestDispatcher dispatcher = getServletContext().getRequestDispatcher(address);
		dispatcher.forward(request, response);
		
	}
	private static final String messagePage = 	"/StockMessage.jsp";
}